In [5]:
import pickle
import numpy as np

In [4]:

ohe_sex=pickle.load(open('/content/ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('/content/ohe_embarked.pkl','rb'))
clf=pickle.load(open('/content/clf.pkl','rb'))

In [8]:
#Assume user input
#Pclass / gender / age / SibSp / Parch(parents child) / Fare / Embarked

test_input=np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [9]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [10]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [11]:
test_input_sex   #for Male[0,1] and Female[1,0]

array([[0., 1.]])

In [12]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [13]:
test_input_embarked

array([[0., 0., 1.]])

In [14]:
test_input_age=test_input[:,2].reshape(1,1)

In [15]:
test_input_age

array([[31.0]], dtype=object)

In [17]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],
                                         test_input_age,test_input_sex,test_input_embarked),axis=1)

In [18]:
test_input_transformed.shape

(1, 10)

In [19]:
clf.predict(test_input_transformed)

array([1])