In [ ]:
import numpy as np

**1. Creating a Matrix using numpy**

In [ ]:
matrix=np.array([[2,1,4],[3,4,5],[8,5,3]])
print(matrix)

[[2 1 4]
 [3 4 5]
 [8 5 3]]


**2.Shape of matrix**

In [ ]:
matrix.shape

(3, 3)

**3. Creating Matrices with Random Values**

In [ ]:
matrix1=np.random.rand(3,3)
print(matrix1)

[[0.97153787 0.7046524  0.10804694]
 [0.53590879 0.27149209 0.73828206]
 [0.83699714 0.92436575 0.29385424]]


In [ ]:
matrix2=np.random.randint(10,size=(3,3))
# creating matrix with random integers
print(matrix2)


[[2 2 4]
 [5 9 0]
 [1 6 2]]


In [ ]:
matrix3=np.ones((3,3),dtype=int)
print(matrix3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


**4. Null matrix**

In [ ]:
matrix4=np.zeros((3,3),dtype=int)
print(matrix4)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


**5. identity matrix**

In [ ]:
matrix5=np.eye(3,dtype=int)
print(matrix5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


**6. Transpose of a Matrix**

In [ ]:
matrix0=np.random.randint(10,size=(3,3))
print(matrix0)


[[5 0 2]
 [9 1 1]
 [8 6 0]]


In [ ]:
matrix9=np.transpose(matrix0)
print(matrix9)

[[5 9 8]
 [0 1 6]
 [2 1 0]]


# **Matrix operation**

In [ ]:
# creating two matrices
matrix1=np.array([[1,3,3],[3,3,4],[2,8,4]])
matrix2=np.array([[1,2,3],[3,2,4],[2,8,4]])

In [ ]:
# creating random two matrix
matrix_3=np.random.randint(10,size=(3,3))
matrix_4=np.random.randint(10,size=(3,3))

In [ ]:
print(matrix1)

[[1 3 3]
 [3 3 4]
 [2 8 4]]


In [ ]:
print(matrix2)

[[1 2 3]
 [3 2 4]
 [2 8 4]]


**1. Adding two Matrices**

In [ ]:
sum=matrix1+matrix2
#sum=np.add(matrix1,matrix2)
print(sum)

[[ 2  5  6]
 [ 6  5  8]
 [ 4 16  8]]


**2. Matrix Subtraction**

In [ ]:
print(matrix_3)

[[7 3 2]
 [9 3 2]
 [2 9 0]]


In [ ]:
print(matrix_4)

[[5 4 4]
 [1 0 0]
 [6 9 6]]


In [ ]:
sub=matrix_3-matrix_4
#sub=np.subtract(matrix_3,matrix_4)
print(sub)



[[ 2 -1 -2]
 [ 8  3  2]
 [-4  0 -6]]


**3. Multiplying 2 Matrices**

In [ ]:
product = np.dot(matrix_3, matrix_4)
print(product)

[[50 46 40]
 [60 54 48]
 [19  8  8]]
