In [ ]:
import numpy as np


In [ ]:
np_array=np.array([1,2,3,4,5],dtype=str)
print(np_array)
type(np_array)

['1' '2' '3' '4' '5']


numpy.ndarray

In [ ]:
m=np.random.random((3,4))
m

array([[0.9698211 , 0.48632137, 0.69113346, 0.34869886],
       [0.14580296, 0.99232443, 0.52347176, 0.18511752],
       [0.89465277, 0.00300624, 0.97668229, 0.66075038]])

In [ ]:
n=np.random.randint(1,10,(3,3))
n


array([[2, 8, 5],
       [5, 5, 5],
       [2, 9, 2]])

Mathmatical operation

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]
print(np.add(list1,list2))
print(np.subtract(list1,list2))
print(np.multiply(list1,list2))
print(np.divide(list1,list2))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
arr=np.array([(1,2,3,4,45,56,67,7,7,)])


arr

array([[ 1,  2,  3,  4, 45, 56, 67,  7,  7]])

In [ ]:
x=np.array([[1,2,3,4],[1,2,3,4],[3,4,5,5]])
print(x)
x.sum(axis=0)
x.sum(axis=1)

[[1 2 3 4]
 [1 2 3 4]
 [3 4 5 5]]


array([10, 10, 17])

In [ ]:
np.where(arr>5)

(array([0, 0, 0, 0, 0]), array([4, 5, 6, 7, 8]))