# **Column Transformer in Machine Learning**

---



In [7]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [8]:
df=pd.read_csv('/content/covid_toy.csv')
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [9]:
df['city'].value_counts()

,count
city,
Kolkata,32
Bangalore,30
Delhi,22
Mumbai,16


In [10]:
df['has_covid'].value_counts()

,count
has_covid,
No,55
Yes,45


In [11]:
df['cough'].value_counts()

,count
cough,
Mild,62
Strong,38


In [12]:
df.isnull().sum()

,0
age,0
gender,0
fever,10
cough,0
city,0
has_covid,0


In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [14]:
X_train

,age,gender,fever,cough,city
73,34,Male,98.0,Strong,Kolkata
88,5,Female,100.0,Mild,Kolkata
11,65,Female,98.0,Mild,Mumbai
31,83,Male,103.0,Mild,Kolkata
55,81,Female,101.0,Mild,Mumbai
...,...,...,...,...,...
2,42,Male,101.0,Mild,Delhi
1,27,Male,100.0,Mild,Delhi
46,19,Female,101.0,Mild,Mumbai
33,26,Female,98.0,Mild,Kolkata


# **1.Hard Method**

In [15]:
si=SimpleImputer()

In [16]:
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.fit_transform(X_test[['fever']])

In [17]:
X_test_fever.shape

(20, 1)

In [18]:
X_train_fever.shape

(80, 1)

In [19]:
X_train_fever

array([[ 98.  ],
       [100.  ],
       [ 98.  ],
       [103.  ],
       [101.  ],
       [102.  ],
       [101.  ],
       [ 98.  ],
       [104.  ],
       [100.75],
       [104.  ],
       [ 98.  ],
       [104.  ],
       [102.  ],
       [100.  ],
       [102.  ],
       [ 99.  ],
       [102.  ],
       [101.  ],
       [100.  ],
       [101.  ],
       [102.  ],
       [ 99.  ],
       [ 99.  ],
       [ 98.  ],
       [103.  ],
       [104.  ],
       [101.  ],
       [ 98.  ],
       [104.  ],
       [104.  ],
       [ 98.  ],
       [100.75],
       [100.75],
       [ 98.  ],
       [104.  ],
       [103.  ],
       [101.  ],
       [103.  ],
       [101.  ],
       [100.  ],
       [ 99.  ],
       [102.  ],
       [101.  ],
       [ 98.  ],
       [103.  ],
       [101.  ],
       [104.  ],
       [101.  ],
       [ 98.  ],
       [100.75],
       [101.  ],
       [100.  ],
       [100.75],
       [ 98.  ],
       [100.  ],
       [104.  ],
       [103.  ],
       [100.75

In [20]:
os=OrdinalEncoder(categories=[['Mild','Strong']])

In [21]:
X_train_cough=os.fit_transform(X_train[['cough']])
X_test_cough=os.fit_transform(X_test[['cough']])

In [22]:
X_train_cough.shape

(80, 1)

In [23]:
X_test_cough.shape

(20, 1)

In [24]:
X_train_cough

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],

In [25]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [26]:
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])

In [27]:
X_train_gender_city.shape


(80, 4)

In [28]:
X_test_gender_city.shape

(20, 4)

In [29]:
X_test_gender_city

array([[1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
X_train_age=X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

In [31]:
X_test_age.shape

(20, 1)

In [32]:
X_train_age

array([[34],
       [ 5],
       [65],
       [83],
       [81],
       [49],
       [14],
       [73],
       [17],
       [82],
       [25],
       [69],
       [42],
       [33],
       [11],
       [ 5],
       [65],
       [82],
       [47],
       [80],
       [49],
       [64],
       [60],
       [25],
       [ 5],
       [48],
       [44],
       [34],
       [40],
       [56],
       [18],
       [31],
       [34],
       [79],
       [80],
       [51],
       [60],
       [38],
       [50],
       [19],
       [27],
       [22],
       [20],
       [ 8],
       [23],
       [73],
       [15],
       [75],
       [51],
       [83],
       [84],
       [20],
       [55],
       [42],
       [12],
       [19],
       [54],
       [70],
       [75],
       [20],
       [71],
       [69],
       [74],
       [65],
       [59],
       [24],
       [11],
       [13],
       [23],
       [68],
       [24],
       [10],
       [46],
       [14],
       [64],
       [42],
       [27],

In [33]:
X_train_transformed = np.concatenate((X_train_age, X_train_fever, X_train_gender_city, X_train_cough), axis=1)
X_test_transformed = np.concatenate((X_test_age, X_test_fever, X_test_gender_city, X_test_cough), axis=1)

In [34]:
X_train_transformed.shape

(80, 7)

In [35]:
X_test_transformed.shape

(20, 7)

# **2. Easy method**

In [36]:
from sklearn.compose import ColumnTransformer

In [37]:
transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [38]:
transformer.fit_transform(X_train).shape

(80, 7)

In [39]:
transformer.transform(X_train)

array([[ 98.  ,   1.  ,   1.  ,   0.  ,   1.  ,   0.  ,  34.  ],
       [100.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,   5.  ],
       [ 98.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,  65.  ],
       [103.  ,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  83.  ],
       [101.  ,   0.  ,   0.  ,   0.  ,   0.  ,   1.  ,  81.  ],
       [102.  ,   0.  ,   0.  ,   1.  ,   0.  ,   0.  ,  49.  ],
       [101.  ,   1.  ,   1.  ,   0.  ,   0.  ,   0.  ,  14.  ],
       [ 98.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  73.  ],
       [104.  ,   0.  ,   0.  ,   0.  ,   1.  ,   0.  ,  17.  ],
       [100.75,   0.  ,   1.  ,   0.  ,   1.  ,   0.  ,  82.  ],
       [104.  ,   0.  ,   1.  ,   0.  ,   0.  ,   0.  ,  25.  ],
       [ 98.  ,   1.  ,   0.  ,   0.  ,   0.  ,   1.  ,  69.  ],
       [104.  ,   0.  ,   1.  ,   0.  ,   0.  ,   1.  ,  42.  ],
       [102.  ,   1.  ,   0.  ,   1.  ,   0.  ,   0.  ,  33.  ],
       [100.  ,   1.  ,   0.  ,   0.  ,   1.  ,   0.  ,  11.  ],
       [102.  ,   0.  ,  

In [40]:
transformer.fit_transform(X_test).shape

(20, 7)

In [41]:
transformer.transform(X_test)

array([[101.22222222,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  10.        ],
       [ 99.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  66.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [ 99.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  72.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.    